title: Tamiro Villazon # your name (or website title) here
logo: "/images/BNT1b.jpeg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist/ Physicist
  <br><br>
  Portfolio
  <br><br>
  <a href="https://www.linkedin.com/in/tamiro-villazon/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
